
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jia
 */
public class GUIWindow extends javax.swing.JFrame {

    SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm:ss a");
    GUIPreferences preferences = new GUIPreferences(this, false);
    
    /**
     * Creates new form GUIWindow
     */
    public GUIWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        GUIWindowPanel = new javax.swing.JPanel();
        LocationField = new javax.swing.JTextField();
        LiveTimeLabel = new javax.swing.JLabel();
        LastUpdatedTimeLabel = new javax.swing.JLabel();
        CurrentlyViewingLocationLabel = new javax.swing.JLabel();
        DisplayContainerPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MenuPreferences = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField3.setText("jTextField3");

        jPanel3.setBackground(new java.awt.Color(192, 241, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(152, 232, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1024, 576));

        GUIWindowPanel.setBackground(new java.awt.Color(192, 241, 255));
        GUIWindowPanel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        GUIWindowPanel.setMaximumSize(new java.awt.Dimension(1024, 576));
        GUIWindowPanel.setMinimumSize(new java.awt.Dimension(1024, 576));
        GUIWindowPanel.setPreferredSize(new java.awt.Dimension(1024, 576));

        LocationField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LocationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LocationField.setText(" Enter Location");
        LocationField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LocationField.setMinimumSize(new java.awt.Dimension(82, 20));
        LocationField.setColumns(30);
        LocationField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationFieldMouseClicked(evt);
            }
        });
        LocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationFieldActionPerformed(evt);
            }
        });
        LocationField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LocationFieldFocusGained(evt);
            }
        });

        Calendar now = Calendar.getInstance();
        LiveTimeLabel = new JLabel (timeFormat.format(now.getTime()));

        new Timer (1000, new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    Calendar now = Calendar.getInstance();
                    LiveTimeLabel.setText(timeFormat.format(now.getTime()));
                }
            }).start();
            LiveTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

            LastUpdatedTimeLabel.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
            LastUpdatedTimeLabel.setText("Updated: \"GetTime\"");

            CurrentlyViewingLocationLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            CurrentlyViewingLocationLabel.setText("Currently Viewing Weather For:____________");

            DisplayContainerPanel.setBackground(new java.awt.Color(200, 200, 200));
            DisplayContainerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
            DisplayContainerPanel.setPreferredSize(new java.awt.Dimension(960, 480));

            jLabel4.setText("Panel for Alex to work on main display");

            javax.swing.GroupLayout DisplayContainerPanelLayout = new javax.swing.GroupLayout(DisplayContainerPanel);
            DisplayContainerPanel.setLayout(DisplayContainerPanelLayout);
            DisplayContainerPanelLayout.setHorizontalGroup(
                DisplayContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DisplayContainerPanelLayout.createSequentialGroup()
                    .addGap(356, 356, 356)
                    .addComponent(jLabel4)
                    .addContainerGap(416, Short.MAX_VALUE))
            );
            DisplayContainerPanelLayout.setVerticalGroup(
                DisplayContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DisplayContainerPanelLayout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(jLabel4)
                    .addContainerGap(244, Short.MAX_VALUE))
            );

            jButton1.setText("jButton1");
            jButton1.setContentAreaFilled(false);
            jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton1.setMargin(new java.awt.Insets(2, 14, 2, 2));
            jButton1.setMaximumSize(new java.awt.Dimension(25, 25));
            jButton1.setMinimumSize(new java.awt.Dimension(25, 25));
            jButton1.setOpaque(false);
            jButton1.setPreferredSize(new java.awt.Dimension(25, 25));
            jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view_refresh_rotated.png"))); // NOI18N
            initRefreshButton();

            javax.swing.GroupLayout GUIWindowPanelLayout = new javax.swing.GroupLayout(GUIWindowPanel);
            GUIWindowPanel.setLayout(GUIWindowPanelLayout);
            GUIWindowPanelLayout.setHorizontalGroup(
                GUIWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GUIWindowPanelLayout.createSequentialGroup()
                    .addComponent(LocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUIWindowPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LiveTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GUIWindowPanelLayout.createSequentialGroup()
                    .addGroup(GUIWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GUIWindowPanelLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(DisplayContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(GUIWindowPanelLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(CurrentlyViewingLocationLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LastUpdatedTimeLabel)))
                    .addContainerGap(34, Short.MAX_VALUE))
            );
            GUIWindowPanelLayout.setVerticalGroup(
                GUIWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GUIWindowPanelLayout.createSequentialGroup()
                    .addComponent(LocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(GUIWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastUpdatedTimeLabel)
                        .addComponent(CurrentlyViewingLocationLabel)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DisplayContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)
                    .addComponent(LiveTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            jButton1.getAccessibleContext().setAccessibleName("RefreshButton");

            jMenu1.setText("Preferences");
            jMenu1.setContentAreaFilled(false);
            jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenu1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jMenu1MouseClicked(evt);
                }
            });
            MenuPreferences.add(jMenu1);

            setJMenuBar(MenuPreferences);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(GUIWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(GUIWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            getAccessibleContext().setAccessibleName("GUIWindow");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        // Preferences handler
        System.out.println("Click Detected");
        preferences.setLocationRelativeTo(null);    // Display in main 
        preferences.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void LocationFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LocationFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationFieldFocusGained

    private void LocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationFieldActionPerformed
        // TODO add your handling code here:
        // DETECTS WHEN ENTER OCCURED
    }//GEN-LAST:event_LocationFieldActionPerformed

    private void LocationFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationFieldMouseClicked

        LocationField.requestFocusInWindow();
        LocationField.selectAll();
//        this.revalidate(); // Don't need
//        this.repaint(); // Don't need
    }//GEN-LAST:event_LocationFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentlyViewingLocationLabel;
    private javax.swing.JPanel DisplayContainerPanel;
    private javax.swing.JPanel GUIWindowPanel;
    private javax.swing.JLabel LastUpdatedTimeLabel;
    private javax.swing.JLabel LiveTimeLabel;
    private javax.swing.JTextField LocationField;
    private javax.swing.JMenuBar MenuPreferences;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void initRefreshButton()
    {
        ImageIcon icon = new ImageIcon(GUIWindow.class.getResource("view_refresh.png"));
        jButton1.setIcon(icon);
    }
    

}
