/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jia
 */
public class GUIPreferences extends javax.swing.JDialog {

    /**
     * Creates new form GUIPreferences
     */
    public GUIPreferences(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        GUIPreferencesPanel = new javax.swing.JPanel();
        CelsiusButton = new javax.swing.JRadioButton();
        FarenheitButton = new javax.swing.JRadioButton();
        UnitsLabel = new javax.swing.JLabel();
        KelvinButton = new javax.swing.JRadioButton();

        buttonGroup1.add(CelsiusButton);
        buttonGroup1.add(FarenheitButton);
        buttonGroup1.add(KelvinButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(320, 190));
        setMinimumSize(new java.awt.Dimension(320, 190));
        setPreferredSize(new java.awt.Dimension(320, 190));
        setResizable(false);

        GUIPreferencesPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        CelsiusButton.setText("Celsius");
        CelsiusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelsiusButtonActionPerformed(evt);
            }
        });

        FarenheitButton.setText("Farenheit");
        FarenheitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarenheitButtonActionPerformed(evt);
            }
        });

        UnitsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UnitsLabel.setText("Units:");

        KelvinButton.setText("Kelvin");
        KelvinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelvinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUIPreferencesPanelLayout = new javax.swing.GroupLayout(GUIPreferencesPanel);
        GUIPreferencesPanel.setLayout(GUIPreferencesPanelLayout);
        GUIPreferencesPanelLayout.setHorizontalGroup(
            GUIPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UnitsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GUIPreferencesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KelvinButton)
                    .addComponent(CelsiusButton)
                    .addComponent(FarenheitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GUIPreferencesPanelLayout.setVerticalGroup(
            GUIPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIPreferencesPanelLayout.createSequentialGroup()
                .addComponent(UnitsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KelvinButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FarenheitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CelsiusButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUIPreferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GUIPreferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CelsiusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelsiusButtonActionPerformed
        // Handle Celsius
    }//GEN-LAST:event_CelsiusButtonActionPerformed

    private void KelvinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelvinButtonActionPerformed
        // Handle Kelvin
    }//GEN-LAST:event_KelvinButtonActionPerformed

    private void FarenheitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarenheitButtonActionPerformed
        // Handle Farenheit
    }//GEN-LAST:event_FarenheitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIPreferences dialog = new GUIPreferences(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CelsiusButton;
    private javax.swing.JRadioButton FarenheitButton;
    private javax.swing.JPanel GUIPreferencesPanel;
    private javax.swing.JRadioButton KelvinButton;
    private javax.swing.JLabel UnitsLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
